name: tufind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\TuFind_Logo.svg
    - assets\images\TuFind_Logo-white.svg
    - assets\images\vector-1.svg
    - assets\images\vector-2.svg
    - assets\images\Separator.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-Bold.ttf
          weight: 700
        - asset: assets\fonts\Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Montserrat-Regular.ttf
          weight: 400
